// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtrPH8Aq6jTjhzbNr_bjM8_Kw_rgu-Dao',
    appId: '1:477601365162:web:2c31ddf8939586231164d3',
    messagingSenderId: '477601365162',
    projectId: 'momapp-wellbeing',
    authDomain: 'momapp-wellbeing.firebaseapp.com',
    storageBucket: 'momapp-wellbeing.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUVoB6u5aNRxYP48sm77RsmIzT9KWVVBY',
    appId: '1:477601365162:android:7a0d7528587f44bc1164d3',
    messagingSenderId: '477601365162',
    projectId: 'momapp-wellbeing',
    storageBucket: 'momapp-wellbeing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4PzamdW-kLSwSMyIrXqLBv4JsD0P9qU',
    appId: '1:477601365162:ios:b05882c3a8b5d2531164d3',
    messagingSenderId: '477601365162',
    projectId: 'momapp-wellbeing',
    storageBucket: 'momapp-wellbeing.appspot.com',
    iosClientId: '477601365162-jj71jm9mnk17caerlitha8fk02h412nh.apps.googleusercontent.com',
    iosBundleId: 'com.appfactory.momapp',
  );
}
